version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - db_data:/app/db_data
    ports:
      - "8000:8000"

volumes:
  db_data: